use_app: hacklab_acl # from apps.yaml
require_acl: "01" # Hex encode version of the ACL bits to require
green_led:
    pin: 21
    time: 2000
red_led:
    pin: 16
    time: 1000
relay:
    pin: 18
    time: 5000
